spring:
  confg:
    activate:
      on-profile: local
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    username: root
    password: gmrfyd12
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    hikari:
      pool-name: stockHikariPool
      maximum-pool-size: 150
      connection-timeout: 10000
  devtools:
    livereload:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 250 # 생성할 수 있는 thread의 총 개수
      min-spare: 50 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 8192 # 수립가능한 connection의 총 개수
    accept-count: 200 # 작업큐의 사이즈
    connection-timeout: 60000 # timeout 판단 기준 시간, 60초

---
spring:
  confg:
    activate:
      on-profile: real
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.21.245:3306/stock_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Qlalfqjsgh1!
    hikari:
      pool-name: stockHikariPool
      maximum-pool-size: 150
      connection-timeout: 10000

server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 250 # 생성할 수 있는 thread의 총 개수
      min-spare: 50 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 8192 # 수립가능한 connection의 총 개수
    accept-count: 200 # 작업큐의 사이즈
    connection-timeout: 60000 # timeout 판단 기준 시간, 60초