spring:
  application:
    name: stock-simulation
  confg:
    activate:
      on-profile: local
  lifecycle:
    timeout-per-shutdown-phase: 20s
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/**
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/react-app/
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/stock_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    hikari:
      pool-name: stockHikariPool
      maximum-pool-size: 30
      connection-timeout: 10000
  devtools:
    livereload:
      enabled: true

server:
  port: 8081
  shutdown: graceful
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    threads:
      max: 100
      min-spare: 50
    max-connections: 8192
    accept-count: 100
    connection-timeout: 60000

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  redirect-uri: ${SUPABASE_REDIRECT_URI}

mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    default-statement-timeout: 30
    default-fetch-size: 100
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.mybatis: DEBUG
    org.springframework.jdbc: INFO
    com.rocky.appstockdata.application.port.out: TRACE