spring:
  confg:
    activate:
      on-profile: local
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    username: root
    password: gmrfyd12
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false

server:
  port: 8081
  servlet:
    context-path: /
---
spring:
  confg:
    activate:
      on-profile: real
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    username: root
    password: Qlalfqjsgh1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.189.231:3306/stock_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false

server:
  port: 8081
  servlet:
    context-path: /